###
GET http://localhost:5020/v1.0/invoke/timer/method/temperaturetimer HTTP/1.1
content-type: application/json

{
    "timeDelay": "5000",
    "timeInterval": "100"
}

###
GET http://localhost:5020/v1.0/invoke/timer/method/heighttimer HTTP/1.1
content-type: application/json

{
    "timeDelay": "5000",
    "timeInterval": "1000"
}

###
GET http://localhost:5020/v1.0/invoke/timer/method/timerchecker HTTP/1.1

